import fs from "node:fs/promises";
import { Presentation, PresentationFile } from "file:///C:/Users/Ankesh%20Phapale/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs";

const OUT = "C:/Users/Ankesh Phapale/Desktop/ORACLE_AIDP_STREAMING/outputs/smart_meter_streaming_demo.pptx";
const p = Presentation.create({ slideSize: { width: 1280, height: 720 } });
const W=1280,H=720, blue="#3D8DFF", light="#6DCBF4", ink="#0B1325", gray="#EEF2F7", muted="#5E6A7D";
function shape(s,g,x,y,w,h,fill="none",line="none"){return s.shapes.add({geometry:g,position:{left:x,top:y,width:w,height:h},fill,line:{style:"solid",fill:line,width:line==="none"?0:1},borderRadius:g==="roundRect"?"rounded-xl":undefined});}
function text(s,t,x,y,w,h,size=24,color=ink,bold=false,align="left"){const q=shape(s,"textbox",x,y,w,h);q.text=t;q.text.style={fontSize:size,color,bold,alignment:align,fontFace:"Arial"};return q;}
function line(s,x1,y1,x2,y2,color="#B8BCC4",width=2){return s.shapes.add({geometry:"line",position:{left:x1,top:y1,width:x2-x1,height:y2-y1},line:{style:"solid",fill:color,width}});}
function header(s,num,title,kicker="SMART METER STREAMING"){text(s,kicker,56,35,500,22,13,blue,true);text(s,title,56,70,1130,54,34,ink,true);text(s,String(num).padStart(2,"0"),1180,38,45,22,14,muted,true,"right");line(s,56,140,1224,140);}
function bullets(s,items,x,y,w){items.forEach((v,i)=>{shape(s,"ellipse",x,y+i*54,11,11,blue);text(s,v,x+24,y-7+i*54,w-24,42,21,ink,false);});}
function footer(s,t){text(s,t,56,675,1000,18,11,muted);}
function metric(s,x,label,value,accent=blue){shape(s,"roundRect",x,205,260,155,gray,"#D6DDE7");text(s,label,x+20,228,220,22,13,muted,true);text(s,value,x+20,263,220,50,30,accent,true);}

// 1
{const s=p.slides.add();s.background.fill="white";text(s,"Smart Meter Streaming\nIntelligence",58,112,650,170,56,ink,true);text(s,"From 15-minute readings to operational insight and next-interval demand forecasts",60,312,610,76,25,muted);shape(s,"roundRect",760,110,390,410,"#0D2854","none");text(s,"10,000",805,170,300,70,62,"#FFFFFF",true,"center");text(s,"smart meters in a live pipeline",800,248,310,35,21,"#D8EBFF",false,"center");line(s,815,325,1090,325,light,3);text(s,"Bronze → Silver → Gold → ML",805,355,300,50,24,"#FFFFFF",true,"center");text(s,"Demo-ready reference architecture",60,616,600,26,17,blue,true);footer(s,"Oracle AIDP + OCI Streaming");}
// 2
{const s=p.slides.add();header(s,2,"The operational challenge is not data collection—it is time to action");bullets(s,["Interval data arrives continuously, but business teams see it too late.","Raw telemetry cannot be trusted until it is validated, deduplicated and contextualized.","Demand, anomaly and outage decisions need a forward-looking view—not yesterday’s report."],70,205,1040);shape(s,"roundRect",760,465,410,120,"#E8F4FF","#B9DAF3");text(s,"The opportunity",790,488,300,24,16,blue,true);text(s,"Turn meter events into a trusted operational decision product.",790,520,340,45,21,ink,true);footer(s,"A streaming design makes each 15-minute interval actionable.");}
// 3 architecture
{const s=p.slides.add();header(s,3,"One pipeline converts meter telemetry into governed operational intelligence");const nodes=[["Meter fleet","10,000 fixed meters"],["OCI Streaming","durable event buffer"],["Bronze","immutable raw JSON"],["Silver","validated interval records"],["Gold","usage + operations"],["ML","next 15-min forecast"]];nodes.forEach((n,i)=>{const x=55+i*195;shape(s,"roundRect",x,260,160,118,i===5?"#0D2854":gray,i===5?"#0D2854":"#C7D0DC");text(s,n[0],x+14,278,132,24,18,i===5?"#FFFFFF":ink,true,"center");text(s,n[1],x+12,315,136,38,13,i===5?"#D8EBFF":muted,false,"center");if(i<nodes.length-1){line(s,x+160,319,x+192,319,blue,3);}});text(s,"Every stage is replayable, monitored and independently schedulable.",78,472,900,32,24,ink,true);bullets(s,["Producer: 10,000 detailed events every 15 minutes","Consumer: batch ingest to Bronze with offset checkpoints","Transform + score: serving tables and future forecast interval"],80,525,960);footer(s,"Bronze preserves evidence; Silver makes it trustworthy; Gold and ML make it useful.");}
// 4
{const s=p.slides.add();header(s,4,"The data product carries context—not just consumption");const cols=[["Electrical","kWh, demand kW, voltage, current, power factor, frequency"],["Operational","quality code, firmware, meter status, outage minutes, tamper flag"],["Network","region, feeder, transformer, service point and tariff"],["Customer","residential, small business, industrial segment"]];cols.forEach((c,i)=>{const x=58+(i%2)*585,y=190+Math.floor(i/2)*190;shape(s,"roundRect",x,y,545,150,gray,"#D6DDE7");text(s,c[0],x+22,y+20,220,28,21,blue,true);text(s,c[1],x+22,y+60,485,62,18,ink,false);});text(s,"This context enables operations, commercial and customer-service use cases from the same event stream.",64,600,1080,35,22,ink,true);footer(s,"Schema v2: granular meter, network and customer attributes.");}
// 5
{const s=p.slides.add();header(s,5,"The same platform serves multiple utility decisions");const use=[["Network operations","Spot demand peaks by feeder or transformer; prioritize investigation."],["Customer programs","Identify consumption patterns by segment; target tariffs and energy advice."],["Revenue assurance","Surface tamper signals, suspect readings and unusual interval behavior."],["Reliability teams","Combine outage indicators and meter status for faster triage."],["Planning & forecasting","Use next-interval forecasts to support dispatch and capacity planning."]];use.forEach((u,i)=>{const y=170+i*85;shape(s,"roundRect",70,y,1140,64,i===4?"#E8F4FF":"#F5F7FA",i===4?"#A9D5F4":"#DCE2EA");text(s,u[0],92,y+18,280,25,20,blue,true);text(s,u[1],400,y+15,770,30,18,ink);});footer(s,"Start with one decision workflow; scale the common data product across teams.");}
// 6
{const s=p.slides.add();header(s,6,"Benefits are delivered through faster visibility, better quality and repeatable automation");metric(s,65,"DATA LATENCY","15-min",blue);metric(s,350,"FLEET COVERAGE","10,000 meters","#167A5B");metric(s,635,"FORECAST HORIZON","next 15 min","#6C4FD3");metric(s,920,"DATA PATH","raw → ML","#C76812");bullets(s,["Operations receive a live, governed view instead of reconciling disconnected extracts.","Data engineering gains replayability, raw evidence and checkpointed consumption.","Business teams gain a segment-aware forecast and an auditable route back to source events."],80,450,1030);footer(s,"Benefits should be measured against agreed operational baselines during pilot.");}
// 7
{const s=p.slides.add();header(s,7,"The demo proves the end-to-end journey—not isolated components");const steps=[["1","Publish","10,000 meter events"],["2","Ingest","Bronze raw events"],["3","Refine","Silver + Gold tables"],["4","Predict","10,000 future forecasts"],["5","Observe","live layer reports"]];steps.forEach((a,i)=>{const x=70+i*230;shape(s,"ellipse",x,220,54,54,blue);text(s,a[0],x,231,54,22,18,"#FFFFFF",true,"center");text(s,a[1],x,300,180,24,21,ink,true);text(s,a[2],x,336,185,50,16,muted);if(i<4)line(s,x+56,247,x+215,247,"#B8BCC4",2);});shape(s,"roundRect",90,480,1100,94,"#0D2854","none");text(s,"Suggested live proof point: show an incoming raw event, its validated Silver record, its Gold aggregate, then the forecast for the next interval.",120,505,1040,42,21,"#FFFFFF",true,"center");footer(s,"Use the dashboard as the narrative bridge between technical flow and business outcome.");}
// 8
{const s=p.slides.add();header(s,8,"A focused pilot can turn this demo into a measurable operating capability");text(s,"Recommended next step",64,190,500,36,28,blue,true);bullets(s,["Select a representative meter cohort and one operational decision to improve.","Agree success measures: data freshness, completeness, forecast error and response time.","Connect the production stream, schedule the pipeline and establish operating ownership."],70,260,850);shape(s,"roundRect",860,220,290,260,"#E8F4FF","#A9D5F4");text(s,"Decision ask",890,250,220,28,21,blue,true,"center");text(s,"Approve a targeted pilot to validate value with real meter data.",885,305,230,90,25,ink,true,"center");text(s,"Built to scale from demo to governed production.",80,590,920,34,26,ink,true);footer(s,"Thank you");}

const file=await PresentationFile.exportPptx(p);await file.save(OUT);
